version: '3.2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    # networks:
    #   - kong
    env_file:
      - .env
    ports:
      - "8001:8001"
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - kong
# networks:
#   kong:
#     driver: bridge
