version: '3.2'
networks:
  kong:
    driver: bridge
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - kong
    env_file:
      - .env
    ports:
      - "8001:8001"
  mongodb:
    hostname: "mongodb"
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - kong
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - kong
