version: '3.8'
networks:
  network:
    driver: bridge
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: colombia
      POSTGRES_USER: aurelion
      POSTGRES_PASSWORD: sol
    ports:
      - "5432:5432"
    networks:
      - network