version: '3.8'
networks:
  kong:
    driver: bridge
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - kong
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - kong